# Prepend your pyenv shims to PATH
PATH := /Users/sarnobat/.pyenv/shims:$(PATH)

all:
	#python3 multiply_nopytorch.py
	python3 multiply.py 4

install:
	python3 -m pip install torch
	python3 -m pip install pyobjc
