all:
	# Warping is the geometric transformation of an image or shape. You’re essentially “bending” or “stretching” the input according to a spatial mapping
	# Morphing is the gradual transformation from one image or shape into another. It usually involves both warping and cross-dissolving.
	pip install opencv-python
	python warp.py