all:
	python3 -m pip install lark
# 	cat ~/mwk.git/apple_notes_read_only/main_iphone.mwk.becomesempty | head -100 | /Users/sarnobat/.pyenv/shims//python3 /Volumes/git/github/python/11_grammar_parser_generator_lark/mwk_parser.py
	cat ~/sarnobat.git/2023/genealogy/rohidekar.ged  | /Users/sarnobat/.pyenv/shims//python3 gedcom.py